//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ShipmentID { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> InsuredValue { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Destination { get; set; }
        public string Status { get; set; }
        public Nullable<int> ShipID { get; set; }
        public Nullable<int> YardID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Ship Ship { get; set; }
        public virtual Yard Yard { get; set; }
    }
}
